"""
Custom Layout Module - GPT-5.2 powered HTML layout generation.

Sprint 5.2: Extends Scene Graph with custom HTML layouts generated by GPT-5.2.
When enabled, after Claude generates a SceneGraph, this module:
1. Sends the SceneGraph to GPT-5.2 to create enhanced HTML
2. Validates the HTML with Playwright
3. Sends both to frontend - uses HTML if valid, SceneGraph as fallback

Usage:
======
    from app.ai.scene.custom_layout import custom_layout_service, layout_validator
    
    # Generate HTML from scene
    result = await custom_layout_service.generate_html(scene, user_request)
    
    if result.success:
        # Validate HTML
        validation = await layout_validator.validate(result.html)
        if validation.is_valid:
            custom_layout = result.html
        else:
            custom_layout = None  # Fall back to scene graph
    
    # Send to device with optional custom layout
    await command_service.display_scene(device_id, scene, custom_layout)
"""

from app.ai.scene.custom_layout.service import custom_layout_service, CustomLayoutResult
from app.ai.scene.custom_layout.validator import layout_validator, ValidationResult

__all__ = [
    "custom_layout_service",
    "CustomLayoutResult",
    "layout_validator",
    "ValidationResult",
]
