"""
Custom Layout Prompts - HTML generation from SceneGraph content.

Architecture:
=============
- SceneGraph = CONTENT (what to show) - generated by backend
- Claude = DESIGN (how to show it) - full creative freedom

The SceneGraph provides the content so Claude can focus on what it does best:
designing beautiful, interactive, engaging visual experiences.
"""

import json
from typing import Dict, Any


def build_custom_layout_prompt(scene: Dict[str, Any], user_request: str = None) -> str:
    """
    Build prompt for Claude to generate custom HTML layout.

    Args:
        scene: SceneGraph with content data
        user_request: Original user request for context

    Returns:
        Prompt string
    """
    if not user_request:
        metadata = scene.get("metadata", {})
        user_request = metadata.get("user_request", "Display content")

    # Extract content from SceneGraph
    global_style = scene.get("global_style", {})
    layout = scene.get("layout", {})
    components = scene.get("components", [])
    animation_hints = scene.get("animation_hints", [])
    scroll_hints = scene.get("scroll_hints", [])

    # Build content summary
    content_data = {
        "user_request": user_request,
        "layout_intent": layout.get("intent", "fullscreen"),
        "style": {
            "background": global_style.get("background", "#0f0f23"),
            "text_color": global_style.get("text_color", "#ffffff"),
            "accent": global_style.get("accent_color", "#7b2cbf"),
        },
        "content": [
            {"type": comp.get("type"), "data": comp.get("data", {})}
            for comp in components
        ],
    }

    if animation_hints:
        content_data["animation_hints"] = animation_hints
    if scroll_hints:
        content_data["scroll_hints"] = scroll_hints

    prompt = f"""## Request
"{user_request}"

## Content (use this data, design freely)
```json
{json.dumps(content_data, ensure_ascii=False, indent=2, default=str)}
```

## Output
Complete standalone HTML (<!DOCTYPE html> to </html>).
Target: 1920x1080 dark theme display.
"""

    return prompt


def get_system_prompt() -> str:
    """System prompt for HTML generation."""
    return """You are an expert HTML/CSS/JS designer.

You receive CONTENT (what to display) and you CREATE the visual experience (how to display it).

The content data is your source material - use it to build something beautiful and engaging.
You have full creative freedom on design, layout, animations, and interactivity.

Use modern web features: CSS flexbox, grid, animations, :has(), scroll-snap.
Use JavaScript when needed for interactivity (quizzes, games, dynamic content).
Make it visually stunning and interactive.

Technical constraints:
- Standalone HTML with inline CSS/JS
- Target: 1920x1080 touchscreen

REQUIRED DATA ATTRIBUTES for interactive content (MUST use these for validation):

For TRIVIA/QUIZ:
- data-trivia="container" on main container
- data-question="N" on each question container (N = question number)
- data-option on each answer option/button
- data-submit on the submit/next button
- data-score on the score display element
- data-feedback on correct/incorrect feedback elements

For GAMES:
- data-game="container" on game container
- data-start on start/play button
- data-score on score display
- data-lives on lives/health display (if applicable)
- data-restart on restart/play-again button

For DASHBOARDS:
- data-dashboard="container" on main container
- data-filter on filter controls
- data-metric on KPI/metric displays
- data-chart on chart containers

INTERACTION REQUIREMENTS (for visual validation):

All interactive elements MUST produce VISIBLE changes when clicked:
- Button clicks should change background color, opacity, or add visual feedback
- Selections should highlight the selected item (border, background, scale)
- Transitions should be visible (not just class changes without CSS effects)
- Feedback elements should appear/disappear with visible styling

The validator takes screenshots before and after clicks to verify visual changes.
If clicking an element produces no visible difference, validation will FAIL.

Good example (visible change):
  .option.selected { background: #4CAF50; transform: scale(1.05); }

Bad example (no visible change):
  .option.selected { /* empty or same as unselected */ }

Output only the HTML code."""
